#!/bin/bash
# AutoMem Stop hook - one-shot LLM-judged storage nudge.
# If no store_memory call happened this session (tracked by
# automem-track-store.sh via the automem-stored-<session_id> sentinel) and
# the transcript shows a substantive session (>= 5 human prompts), emits
# hookSpecificOutput.additionalContext asking Claude once to store durable
# facts. Claude Code renders Stop-hook additionalContext as a visible
# "Stop hook feedback" block and rewakes Claude for one closing turn;
# suppressOutput only hides raw stdout, NOT that block. The nudge is one
# short line and gated to substantive sessions to keep that visible cost
# rare and well-timed.
# Advisory only: never blocks, never exits 2.
# Generated by scripts/sync-memory-policy.ts. Do not edit by hand.

SESSION_ID=""
EVENT_NAME="Stop"
TRANSCRIPT_PATH=""
if [ ! -t 0 ]; then
  HOOK_INPUT=$(cat 2>/dev/null || true)
  SESSION_ID=$(printf '%s' "$HOOK_INPUT" | sed -n 's/.*"session_id"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n 1 | tr -cd 'A-Za-z0-9_-')
  EVENT_RAW=$(printf '%s' "$HOOK_INPUT" | sed -n 's/.*"hook_event_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n 1)
  TRANSCRIPT_PATH=$(printf '%s' "$HOOK_INPUT" | sed -n 's/.*"transcript_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n 1)
  if [ "$EVENT_RAW" = "SubagentStop" ]; then
    EVENT_NAME="SubagentStop"
  fi
fi

# No session_id -> no dedup possible. Stay silent rather than risk a
# nudge -> conversation continues -> Stop -> nudge loop.
if [ -z "$SESSION_ID" ]; then
  exit 0
fi

# Stored sentinel: a store_memory call already happened -> nothing to nudge.
# Nudged sentinel: we already nudged once -> stay silent on re-entry.
STORED_SENTINEL="${TMPDIR:-/tmp}/automem-stored-${SESSION_ID}"
NUDGED_SENTINEL="${TMPDIR:-/tmp}/automem-stop-nudged-${SESSION_ID}"
if [ -e "$STORED_SENTINEL" ] || [ -e "$NUDGED_SENTINEL" ]; then
  exit 0
fi

# Substantive-session gate: the nudge costs a visible feedback block plus a
# full-context rewake turn, so it only fires once the session has enough
# human prompts to plausibly contain something durable. Human prompts ~=
# transcript user entries that are neither tool results nor meta entries.
# No readable transcript or an unparseable count -> stay silent (silence is
# the safe failure; Windows transcript paths arrive JSON-escaped and
# unreadable here, so the gate is effectively POSIX-only).
if [ -z "$TRANSCRIPT_PATH" ] || [ ! -r "$TRANSCRIPT_PATH" ]; then
  exit 0
fi
HUMAN_TURNS=$(grep '"type"[[:space:]]*:[[:space:]]*"user"' "$TRANSCRIPT_PATH" 2>/dev/null | grep -v 'tool_use_id' | grep -cv '"isMeta"[[:space:]]*:[[:space:]]*true')
case "$HUMAN_TURNS" in
  ''|*[!0-9]*) exit 0 ;;
esac
# Below the threshold: exit WITHOUT writing the nudged sentinel so a later
# Stop in this session can still nudge once the conversation crosses it.
if [ "$HUMAN_TURNS" -lt 5 ]; then
  exit 0
fi

# Write the sentinel before emitting so a re-entrant Stop sees it. If it
# can't be created (e.g. TMPDIR not writable), the once-per-session guarantee
# is gone, so stay silent rather than nudge on every Stop.
if ! : > "$NUDGED_SENTINEL" 2>/dev/null; then
  exit 0
fi

printf '{"suppressOutput":true,"hookSpecificOutput":{"hookEventName":"%s","additionalContext":%s}}\n' "$EVENT_NAME" '"No memories were stored this session. If a durable preference, correction, decision, pattern, or insight emerged, store it now via the store_memory tool (recall related -> store -> verify -> associate; bare tags). Do NOT store session summaries, progress notes, or confirmations - if nothing qualifies, reply with exactly: Nothing durable to store."'

# Advisory hook: always succeed even if printf hit a write error, so Claude
# Code never treats the Stop hook as failed and discards the JSON.
exit 0
